apiVersion: v1
name: frepple
version: 1.0
appVersion: 6.16.0
description: FrePPLe 6
home: https://www.opensourceintegrators.com
icon: https://github.com/ursais.png?width=64
keywords:
- advanced planning system
- manufacturing
- purchasing
- distribution
- planning
- material requirement
sources:
- https://github.com/ursais/docker
maintainers:
- name: Open Source Integrators
  email: support@opensourceintegrators.com
engine: gotpl
